openapi: 3.0.1
info:
  title: test2
  description: Import from "lamin-function-test" Function App
  version: '1.0'
servers:
  - url: https://apim-lamin-test.azure-api.net/test2
paths:
  /HttpTrigger1:
    get:
      summary: HttpTrigger1
      operationId: get-httptrigger1
      responses:
        '200':
          description: 
    post:
      summary: HttpTrigger1
      operationId: post-httptrigger1
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
