# This is a basic workflow to help you get started with Actions
name: CD-API-Import

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  #   paths:
  #         - api-specs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Import_API_Specifications:
    name: 'Import_API_Specifications'
    runs-on: ubuntu-latest
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Login to Azure CLI
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Download the APIM artifact
      - uses: actions/download-artifact@v4
        with:
          name: apim-artifact

      - run: echo "APIM_DETAILS=$(jq -c . < apim_details.json)" >> $GITHUB_ENV

      # Get changed file names (efficiently)
      - name: Get changed API specification files
        run: |
          changed_files=$(git diff --name-only --diff-filter=d HEAD~ 'api-specs/*')  # Focus on deleted/modified files
          echo "CHANGED_FILES=$(changed_files)" >> $GITHUB_ENV

      # Print changed file names
      - name: Print changed API specifications
        run: |
          echo "List of changed API specifications:"
          for file in ${{ env.CHANGED_FILES }}; do
            echo "  - $file"
          done

      # Loop through changed files and execute Azure CLI script for each
      - name: Run Azure CLI script for each changed file
        run: |
          for file in ${{ env.CHANGED_FILES }}; do
            FILENAME=$(basename "$file")  # Extract filename
            az apim api import -g ${{ fromJson(env.APIM_DETAILS).resource-group-name }} --service-name ${{ fromJson(env.APIM_DETAILS).apim-name }} --path /$FILENAME --specification-path api-specs/"$file" --specification-format OpenApiJson
          done

