# This is a basic workflow to help you get started with Actions
name: CD-API-Import

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
          - api-specs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  actions: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Import_API_Specifications:
    name: 'Import_API_Specifications'
    runs-on: ubuntu-latest
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Login to Azure CLI
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Download the APIM artifact
      - name: Download APIM artifact
        uses: actions/download-artifact@v4
        with:
          repository: ${{ github.repository }}          
          path: terraform/*

      # Get the APIM info
      - name: Get APIM Detail      
        run: echo "APIM_DETAILS=$(jq -c . < apim_details.json)" >> $GITHUB_ENV

      # Get API files committed
      - name: Get changed files from last commit
        run: |
            git fetch origin main
            changedFiles=$(git diff --name-only --diff-filter=AM HEAD~1 --)
            echo "$changedFiles"                                  

            changedFilesString=""
            while IFS= read -r line; do
                if [[ -n "$changedFilesString" ]]; then
            	    changedFilesString+=","
                fi            
                changedFilesString+="$line"
            done <<< "$changedFiles"

            echo $changedFilesString
            echo "CHANGED_FILES=$changedFilesString" >> $GITHUB_ENV

      # Import APIs to APIM
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            IFS=', ' read -r -a Files <<< "${{env.CHANGED_FILES}}"
            for file in "${Files[@]}"
            do
              echo "$file"
              # az apim api import -g ${{ fromJson(env.APIM_DETAILS).resource-group-name }} --service-name ${{ fromJson(env.APIM_DETAILS).apim-name }} --path /$FILENAME --specification-path api-specs/"$file" --specification-format OpenApiJson
            done  

