# This is a basic workflow to help you get started with Actions
name: test2

# Controls when the workflow will run
on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Import_API_Specifications:
    name: 'Import_API_Specifications'
    runs-on: ubuntu-latest
    environment: production
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Get changed file names (efficiently)
      - name: Azure CLI script
        run: |
            git fetch origin main
            changedFiles=$(git diff --name-only --diff-filter=AM HEAD~1 --)
            echo "$changedFiles"                                  

            changedFilesString = ""
            for file in "${changedFiles[@]}"
            do
              echo " filename - $file"
              FILENAME=$(basename "$file") 
              echo " basename = $FILENAME"
              changedFilesString+= ",$FILENAME"
            done

            echo $changedFilesString
            echo "CHANGED_FILES=$changedFilesJson" >> $GITHUB_ENV

      # # Get changed file names (efficiently)
      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |

